### PR TITLE
Update to cmake build

### PR DESCRIPTION
**Pull request by markschatza**
Hey thanks for the awesome plugin! Noticed your updated cmake branch didn't follow the same structure as the default OE plugins.  Here's a version that follows it!

Best,
Mark

### CODE REVIEW

**Comment by alejoe91** [comment]
HI @markschatza 

Thanks for this man! Super appreaciated!! :)

**Comment by alejoe91** [comment]
Before merging can you check if this branch is up to date? https://github.com/CINPLA/logic-gate-plugin/tree/update/LogicGate 

I should have marged to master before eheheh

Any particular reason why you created a new `Source` folder?

**Comment by markschatza** [comment]
Hey @alejoe91 

Oh I'm sure your update branch works great. :) I just like to use https://github.com/open-ephys-plugins/OEPlugin as the base for my plugins to keep everything standard. Plus their cmake file has some OS specific things that may improve performance/stability on different platforms. 

As for specifically why a source folder. I believe they put it there so they can just .gitignore everything in the build folder easily.

Quick question, do your events show up in the LFP viewer when you use this plugin?

**Comment by alejoe91** [comment]
Thanks for the clarification! :) Merging this then.
Would you have time to make the same changes for these two plugins? 
- https://github.com/CINPLA/tracking-plugin
- https://github.com/CINPLA/sync-plugin

I haven't use the template there neither! (Actually just realized there is a template now :))

Regarding the LFP viewer, unfortunately they won't show, because the LFP viewer only plots real ttl from the fpga.

**Comment by markschatza** [comment]
Yep! :)

And hmm ok, I think I may have a fix for that. Let me see!

**Comment by alejoe91** [comment]
Thanks a lot!!!

**Pull request merged**
